services:
  - type: web
    name: roomreservation-app
    env: docker
    plan: free
    dockerfilePath: ./RoomResertionApp/Dockerfile
    dockerContext: ./RoomResertionApp
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:8080
      - key: ConnectionStrings__DefaultConnection
        sync: false
